name: Train Model and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python train.py

    - name: Save Model
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download model artifact
      uses: actions/download-artifact@v2
      with:
        name: model
        path: model.pkl

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USER: ${{ secrets.PA_USER }}
        GITHUB_REPOSITORY_NAME: iris_classification_model_2
      run: |
        curl -H "Authorization: Token ${PA_API_TOKEN}" -H "Content-Type: application/json" -X DELETE https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webapps/${GITHUB_REPOSITORY_NAME}
        curl -H "Authorization: Token ${PA_API_TOKEN}" -H "Content-Type: application/json" -X POST https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webapps/ -d "{\"domain\": \"${GITHUB_REPOSITORY_NAME}.pythonanywhere.com\"}"
        curl -H "Authorization: Token ${PA_API_TOKEN}" -H "Content-Type: application/json" -X POST https://www.pythonanywhere.com/api/v0/user/${PA_USER}/webapps/${GITHUB_REPOSITORY_NAME}/reload

#     - name: Install Heroku CLI
#       run: curl https://cli-assets.heroku.com/install.sh | sh

#     - name: Deploy to Heroku
#       run: |
#         cd ${{ github.workspace }}
#         heroku container:login
#         heroku create iris-heroku-app-mlops
#         git push heroku HEAD:main
#       env:
#         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#         HEROKU_APP_NAME: iris-heroku-app-mlops
#         HEROKU_EMAIL: hamid.bekam@gmail.com
